[package]
name = "automerge-python"
version = "0.1.0"
authors = ["Alex Good <alex@memoryandthought.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "automerge_backend"
crate-type = ["cdylib"]

[dependencies]
automerge = { git = "https://github.com/automerge/automerge.git", rev = "b34b46fa1654ebf64c1beb0c8bd83323c2a55e90" }
ouroboros = "0.15.6"

[dependencies.pyo3]
version = "0.18.1"
features = ["extension-module"]
